version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - '5432:5432'
    volumes:
      - ./database/docker:/docker-entrypoint-initdb.d # 挂载 init.sql 文件
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    restart: always
    command: ['redis-server', '--requirepass', 'redis']
    environment:
      REDIS_PASSWORD: redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

# you need to mkdir before docker-compose `mkdir -p ./.data/pg && mkdir -p ./.data/redis`
volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./.data/pg
  redis_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./.data/redis
