CREATE TABLE public.user (
    id SERIAL PRIMARY KEY,
    user_id TEXT,
    language TEXT,
    current_language TEXT,
    origin_language TEXT,
    ip TEXT,
    ip_country_code TEXT,
    first_ip TEXT,
    first_ip_country_code TEXT,
    register_time BIGINT,
    recent_view_time BIGINT,
    is_deleted BOOLEAN,
    create_time BIGINT,
    delete_time BIGINT,
    last_active_time BIGINT,
    activedays INTEGER,
    user_consecutive_active_days INTEGER,
    last_checkin_date TEXT,
    consecutive_checkin_days INTEGER,
    subscription JSONB,
    subscription_times INTEGER,
    login_time BIGINT,
    user_category_ids TEXT[],
    index_id TEXT,
    device_id TEXT,
    bind_type TEXT,
    bind_id TEXT,
    bind_info JSONB,
    nickname TEXT,
    avatar TEXT,
    device_brand TEXT,
    device_model TEXT,
    os TEXT,
    os_version TEXT,
    client_version TEXT,
    carrier TEXT,
    mac TEXT,
    imei TEXT,
    time_zone TEXT,
    app_id TEXT,
    install_time BIGINT,
    android_id TEXT,
    ga_id TEXT,
    simulator BOOLEAN,
    firebase_token TEXT
);

CREATE INDEX idx_device_id ON public.user (device_id);
CREATE UNIQUE INDEX idx_user_id ON public.user (user_id);
CREATE UNIQUE INDEX idx_index_id ON public.user (index_id);